### ISSUE TITLE
Is it possible to parse the nested struecture, such as asn.1 output file?

### ISSUE THREAD

**Issue by jufei** [tijo-io/pytijo#8]
hi:

Is it possible use it to parse the nested text, like:

cellAccessRelatedInfo {
      plmn-IdentityList {
        {
          plmn-Identity {
            mcc {
              2,
              6,
              2
            },
            mnc {
              0,
              3
            }
          },
          cellReservedForOperatorUse notReserved
        },
      },
    },

Thanks.

**Comment by joncastro** [comment]
@jufei can you please share the template and the output that you are trying to parse?

Lists can also be parsed, you just need to provide the `@id`. For example,

```
{
 "interfaces": [
    {
    "@id": "^([a-z]+\\d{1,2}):",
    "ipv4_address": "inet (\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})",
    }
]
}
```

**Comment by jufei** [comment]
[sib.log](https://github.com/tijo-io/pytijo/files/4068704/sib.log)

The sib.log is the file I need to parse, as you see, it is nested structure.

I wish to parse it to a dict.

**Comment by joncastro** [comment]
In that case it is easy. I show you a couple of examples:

If you wish to keep a dictionary with a single level 
```
{
 "ac-BarringForEmergency":"ac-BarringForEmergency (\\S+)",
 "numberOfRA-Preambles":"numberOfRA-Preambles (\\S+)",
 "sizeOfRA-PreamblesGroupA":"sizeOfRA-PreamblesGroupA (\\S+)",
 "messageSizeGroupA":"messageSizeGroupA (\\S+)",
 "messagePowerOffsetGroupB":"messagePowerOffsetGroupB (\\S+)",
 "powerRampingStep":"powerRampingStep (\\S+)",
 "preambleInitialReceivedTargetPower":"preambleInitialReceivedTargetPower (\\S+)"
}
```
Above template produces following output.
```
$  tijo --tijo-template sib_example1.tijo  cat sib.log --tijo-output-beauty
{
    "sizeofra-preamblesgroupa": "n32,",
    "powerrampingstep": "dB2,",
    "preambleinitialreceivedtargetpower": "dBm-96",
    "messagepoweroffsetgroupb": "dB10",
    "messagesizegroupa": "b144,",
    "ac-barringforemergency": "FALSE",
    "numberofra-preambles": "n40,"
}
```


Or if you wish to have multiple dictionary levels
```
{
   "ac-BarringInfo":{
      "ac-BarringForEmergency":"ac-BarringForEmergency (\\S+)"
   },
   "radioResourceConfigCommon":{
      "rach-ConfigCommon":{
         "preambleInfo":{
            "numberOfRA-Preambles":"numberOfRA-Preambles (\\S+)",
            "preamblesGroupAConfig":{
               "sizeOfRA-PreamblesGroupA":"sizeOfRA-PreamblesGroupA (\\S+)",
               "messageSizeGroupA":"messageSizeGroupA (\\S+)",
               "messagePowerOffsetGroupB":"messagePowerOffsetGroupB (\\S+)"
            }
         },
         "powerRampingParameters":{
            "powerRampingStep":"powerRampingStep (\\S+)",
            "preambleInitialReceivedTargetPower":"preambleInitialReceivedTargetPower (\\S+)"
         }
      }
   }
}
```
Above template produces following output.
```
$  tijo --tijo-template sib_example2.tijo  cat sib.log --tijo-output-beauty
{
    "ac-barringinfo": {
        "ac-barringforemergency": "FALSE"
    },
    "radioresourceconfigcommon": {
        "rach-configcommon": {
            "preambleinfo": {
                "preamblesgroupaconfig": {
                    "messagepoweroffsetgroupb": "dB10",
                    "sizeofra-preamblesgroupa": "n32,",
                    "messagesizegroupa": "b144,"
                },
                "numberofra-preambles": "n40,"
            },
            "powerrampingparameters": {
                "powerrampingstep": "dB2,",
                "preambleinitialreceivedtargetpower": "dBm-96"
            }
        }
    }
}
```
The idea of tijo templates is that you build directly the json output that you wish, just be aware that the "string" values are considered regular expression. For example,

```
{
 "key" : "regular expression"
}
```

```
{
 "key1" : {
    "key2":  "regular expression"
  }
}
```

if you define a regular expression into a list `["regular expression"] then Tijo will consider the regular expression could provide more than one value and the output is a list too.

```
{
 "key" : ["regular expression"]
}
```

**Comment by jufei** [comment]
hi：
   Thanks for your quickly response.

   Yes, I need the multiple dictionary level;

   But my data structure is not fixed; I mean all the fields name are not fixed; (for diffferetnt sib message, the fields and level are different), I can not use a fixed template to parse it.

**Comment by joncastro** [comment]
As of today, Tijo requires a template per type of message.

You said your output is asn.1 based, right? if you do not want to have multiple Tijo templates (a template per type of sib message) then you would need to either build your own asn.1 parser or find one available in internet.

**Comment by jufei** [comment]
Yes, I got your mean.
What I got is the output text file, all these asn.1 parser are used to parse binary asn.1 data file, not text file. That is why I need to do text parse.

Anyway, Thanks!
